server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
    
  
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/login/**
          filters:
            - name: CircuitBreaker
              args:
                name: AUTHENTICATION-SERVICE
                
        - id: clients
          uri: lb://clients
          predicates:
            - Path=/clients/**
          filters:
            - name: CircuitBreaker
              args:
                name: clients
                
        - id: contract
          uri: lb://contract
          predicates:
            - Path=/contract/**
          filters:
            - name: CircuitBreaker
              args:
                name: contract
                
       
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost    



